name: Daily DecoTV Scraper
on:
  workflow_dispatch:   # ← 新增這一行
  schedule:
    - cron: '0 18 * * *'  # UTC 18:00 = 台灣隔天 02:00
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install --no-cache-dir -r requirements.txt
      - run: python rss_article.py
      - run: python scrape.py
        env:
          API_URL: ${{ secrets.API_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          RSS_URL: 'https://decotv.com.tw/feed/'
          POSTED_FILE: './posted.txt'
